version: ‘3’
services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: paasdb
      MYSQL_USER: paasdb_user
      MYSQL_PASSWORD: pass123
    ports:
      – “6033:3306”
    volumes:
      – dbdata:/var/lib/mysql

  build:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - appdata:/home/dz12/App42PaaS-Java-MySQL-Sample/target/
      - proddata:/home/dz12/App42PaaS-Java-MySQL-Sample/WebContent/

  prod:
    build:
      context: ./prod
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - appdata:/usr/local/tomcat/webapps/

volumes:
  dbdata:
  appdata:
  proddata: