version: '3.7'
services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Pa$$w0rd
      MYSQL_DATABASE: paasdb
      MYSQL_USER: paasdb_user
      MYSQL_PASSWORD: pass123
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      timeout: 5s
      retries: 5
    volumes:
      – dbdata:/var/lib/mysql
    volumes:
      dbdata: 

  build:
    build:
      context: ./build
      dockerfile: Dockerfile
    volumes: 
      - appdata:/home/dz12/App42PaaS-Java-MySQL-Sample/target/
      - proddata:/home/dz12/App42PaaS-Java-MySQL-Sample/WebContent/

  prod:
    build:
      context: ./prod
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - appdata:/usr/local/tomcat/webapps/

volumes:
  dbdata:
  appdata:
  proddata: